currdir=$(shell pwd)
builddir=${currdir}/build
downloadsdir=$(shell cd ~; realpath -m ./downloads)
repodir=$(builddir)/bin
repo=$(repodir)/repo
repourl=http://commondatastorage.googleapis.com/git-repo-downloads/repo
repogiturl=https://gerrit.googlesource.com/git-repo
yoctodir=$(builddir)/yocto
yoctourl=https://github.com/Advantech-IIoT/yocto.git
yoctobranch=project/wise710a1
yoctomanifest=default.xml
yoctomachine=imx6dlwise710a1
yoctobuilddir=build.$(yoctomachine)
yoctodistro=x11
SHELL=/bin/bash
export YOCTO_DL_DIR="/root/wise710a1/downloads"
export YOCTO_TMPDIR="/root/wise710a1/tmp"
export YOCTO_SSTATE_DIR="/root/wise710a1/sstate-cache"
